### PR TITLE
Use starlet to process requests in parallel

### PR DESCRIPTION
**Pull request by baoshan**
This PR adds a `-e MAX_WORKERS`option which will pass to Starlet, thus increase performance on multi-core machines.

Please check the modifications, Thanks.

### CODE REVIEW

**Comment by sparklyballs** [comment]
The cleanup command needs to be in the same run block it originally was, due to the way docker caches layers.
If you have files in a layer and end operations in that layer, by starting a new run block, those files are cached and deleting them in subsequent layers doesn't decrease the size of the completed image.

**Comment by baoshan** [comment]
I think I miss some fundamentals knowledge. But, when the cleanup command is in the same block, the whole `RUN` block fails with no obvious error printed.

Is that due to the max command line length reached? (blind guessing).

Could you kindly help?

**Comment by sparklyballs** [comment]
test this please

**Comment by sparklyballs** [comment]
retest this please

**Comment by baoshan** [comment]
It builds fine.

```
me$ git branch
  master
* starlet

me$ docker build -t baoshan/musicbrainz .
Successfully built c367a87359f9

me$ docker create --name=musicbrainz -e MAX_WORKERS=8 -e BRAINZCODE=XXXX  -p 5000:5000 -p 5432:5432 baoshan/musicbrainz
musicbrainz
```

I'm rebuilding the database now. Will report back.

**Comment by sparklyballs** [comment]
the test messages, i won't repeat them in this comment for obvious reasons, are commands to the bot to get our CI server to build the PR.

**Comment by sparklyballs** [comment]
i retested the build because i had to take out the startup test we have on the CI server, it started downloading the data dump and would have eventually eaten up the limited space on the server.

**Comment by sparklyballs** [comment]
retest this please

**Comment by sparklyballs** [comment]
@baoshan how did the database build go ?

**Comment by baoshan** [comment]
At the current `starlet` branch, the server starts well and delivers expected performance as well.

Thanks @sparklyballs !

**Comment by sparklyballs** [comment]
going to close this, i'm implementing it into a fork at the moment.
doing a slight rewrite of the main dockerfile for clarity, taking out the line for coro as the cpanm latest version now builds, and less noise in jenkins logs.

see PR #13

**Pull request closed without merging**
