### PR TITLE
Complete rewrite.

### PR DESCRIPTION
**Pull request by sparklyballs**
Went right back to ubuntu 14.04 baseimage on this one.
Phusion is too fat.

As it stands at the moment musicbrainz needs to remain on trusty as one of the perl depedencies does not work with the perl version in xenial. The developer of that dependency's current stance is that he will not be supporting perl 5.22.

Using S6 overlay. 
The current lsio image on this comes out at 1.7GB, rewrite is just under 630MB.

### CODE REVIEW

**Comment by baoshan** [comment]
Thanks @sparklyballs!

Wish we can have the update sooner.

**Comment by baoshan** [comment]
Could someone kindly review the rewrite and update docker hub?

Thanks a lot.

**Comment by baoshan** [comment]
When creating a new container, I encountered below error:

```
fetching latest dump from musicbrainz, if this section fails try again later as musicbrainz dump may not be fully uploaded 
to their site
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 64.8M  100 64.8M    0     0  57.7M      0  0:00:01  0:00:01 --:--:-- 57.7M
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 20.6M  100 20.6M    0     0  40.5M      0 --:--:-- --:--:-- --:--:-- 40.5M
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  121M  100  121M    0     0  5677k      0  0:00:21  0:00:21 --:--:-- 5111k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (78) RETR response: 550
[cont-init.d] 30-initialise-database: exited 78.
[cont-init.d] 40-config-redis: executing... 
[cont-init.d] 40-config-redis: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[352] 16 Jun 18:13:23.555 # Server started, Redis version 2.8.4
[352] 16 Jun 18:13:23.555 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
```

And the initialisation process hangs. It seems something wrong from the `30-initialise-database` phase. Could @sparklyballs confirms the problem?

Thank you.

**Comment by j0nnymoe** [comment]
The reason that this is failing is at the top of your paste.
"fetching latest dump from musicbrainz, if this section fails try again later as musicbrainz dump may not be fully uploaded to their site"

**Comment by baoshan** [comment]
My appreciation, @j0nnymoe. MusicBrainz have some troubles with their server upgrades for two days. Will try again later.

**Pull request merged**
