### PR TITLE
Update MusicBrainz logo and fix name caps

### LINKED ISSUE #75: MusicBrainz logo on readme is outdated
Hi!

The project readme (and possibly other places) use the old MusicBrainz logo. Updated ones are at
https://github.com/metabrainz/metabrainz-logos/tree/master/final-logos-v2/MusicBrainz/VECTOR 
/ https://github.com/metabrainz/metabrainz-logos/tree/master/final-logos/MusicBrainz/VECTOR in case you feel like updating it! (I'd send a PR but it seems to be stored in an archived repo).

Nicolás from MusicBrainz

### PR DESCRIPTION
**Pull request by reosarevok**
Closes #75

Also fixed the caps (the project name is MusicBrainz - which won't work via project_name|capitalize so I just hardcoded it) and a couple typos I saw.

### CODE REVIEW

**Comment by ironicbadger** [comment]
Ping @nemchik - LGTM but seeing as you were on OG issue can you approve and merge?

**Comment by aptalca** [comment]
@reosarevok thanks for the pr
Please pr the logo to this repo: https://github.com/linuxserver/docker-templates/tree/master/linuxserver.io/img
And reference it here.

Thanks

**Comment by reosarevok** [comment]
I did already, https://github.com/linuxserver/docker-templates/pull/201 (merged)

**Comment by aptalca** [comment]
Great. Can you update this pr to remove the icon file upload and change the logo link to point to the other repo?
Thanks

**Comment by reosarevok** [comment]
I thought I fixed it as required but CI seems unhappy :) Anything missing?

**Comment by aptalca** [comment]
it looks like musicbrainz hasn't been building successfully for some time, likely an issue at head

**Comment by reosarevok** [comment]
Do you need anything else from me here?

**Pull request merged**
